database:
    driver: 'pdo_mysql'
    host: 'mysql8033.xserver.jp'
    dbname: 'ancharme_ec2'
    port: ''
    user: 'ancharme_ec2'
    password : '5x4r3slntx'
    charset: utf8
    defaultTableOptions: { collate: utf8_general_ci }
