<?php

namespace Plugin\SimpleCoupon\Repository;

use Doctrine\ORM\EntityRepository;
use Monolog\Logger;
use Eccube\Util\Str;

/**
 * ConditionCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionCustomerRepository extends EntityRepository
{
	
	protected $app;
	
	public function setApplication($app)
	{
		$this->app = $app;
	}
	
	
	public function getQueryBuilderBySearchDataForAdmin($searchData){
		
		$qb = $this->createQueryBuilder('con')
				->addSelect('cus')
				->innerJoin('con.Customer', 'cus');
		
		$qb->andWhere('con.couponId = :coupon_id')->setParameter('coupon_id', $searchData['coupon_id']);
		$qb->andWhere('cus.del_flg = :del_flg')->setParameter('del_flg', '0');
		
		
		// customer_id
		if (isset( $searchData['customer_id']) && Str::isNotBlank($searchData['customer_id'])) {
			$qb->andWhere('con.customerId = :customer_id')
			   ->setParameter('customer_id', $searchData['customer_id']);
		}
		
		// Order By
		$qb->addOrderBy('con.customerId', 'ASC');
		
		return $qb;
		
	}
	
}
