<?php

namespace Plugin\SimpleCoupon\Repository;

use Doctrine\ORM\EntityRepository;
use Monolog\Logger;
use Eccube\Util\Str;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
	
	protected $app;
	
	public function setApplication($app)
	{
		$this->app = $app;
	}
	
	
	
	/**
	 * クーポンで支払い不要にする場合の、支払いIDを取得する
	 * @return NULL
	 */
	public function getCouponPaymentId()
	{
		$qb = $this->createQueryBuilder('c');
		$query = $qb->getQuery();
		$result = $query->getResult();
		
		if(count($result)>0){
			return $result[0]->getCouponPaymentId();
		}else{
			return null;
		}
	}
	
	
	/**
	 * 
	 * @return \Plugin\SimpleCoupon\Entity\Config|object|NULL
	 */
	public function findOrCreate()
	{
		$list = $this->findAll();
		if(count($list)==0){
			//初期登録
			$Config = new \Plugin\SimpleCoupon\Entity\Config();
		}else{
			$Config = $list[0];
		}
		return $Config;
	}
	
}
