<?php

namespace Plugin\GoqsmilePlugin\Repository;

use Doctrine\ORM\EntityRepository;
use Eccube\Application;
use Plugin\GoqsmilePlugin\Entity\Config;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
  /**
   * Get Entity from table.
   * @param Application $app Get from EC-CUBE3.
   * @param int $id  Entity id.
   */
  public function getEntity($id = 1)
  {
      return $this->find($id);
  }

  /**
   * Insert  configuration data to table.
   * @param Application $app Get from EC-CUBE3.
   * @param Request $request HTTP request from form submission.
   */
  public function setEntity(Application $app, Request $request)
  {
      $entity = new Config();
      $entity->setId(1);
      $this->setFormDataToEntity($request, $entity);
      $app['orm.em']->persist($entity);
      $app['orm.em']->flush();
  }

  /**
   * Update  configuration data in table
   * @param Application $app Get from EC-CUBE3.
   * @param Request $request HTTP request from form submission.
   */
  public function replaceEntity(Application $app, Request $request)
  {
      $entity= $this->getEntity(1);
      if($entity){
        $this->setFormDataToEntity($request, $entity);
      }else{
        $this->setEntity($app, $request);
      }
      $app['orm.em']->flush();
  }

  /**
   * Set request data to  Entity.
   * @param Request $request HTTP request from form submission.
   * @param  $entity Entity for  configuration.
   */
  private function setFormDataToEntity(Request $request, Config $entity)
  {
      $entity->setAppId($request->request->get('goqsmileplugin_config')['app_id']);
  }

  /**
   * Set form data from  Entity.
   * @param Application $app Get from EC-CUBE3.
   * @param Form $form Form to handle credential.
   */
  public function setEntityToForm(Form $form)
  {
      $entity = $this->getEntity(1);
      if ($entity) {
          $form->get('app_id')->setData($entity->getAppId());
          return true;
      }

      return false;
  }
}
