<?php
/*
 * Copyright(c) 2015 GMO Payment Gateway, Inc. All rights reserved.
 * http://www.gmo-pg.com/
 */

namespace Plugin\GmoPaymentGateway\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmoOrderPaymentRepository extends EntityRepository
{
    /** @var array */
    public $config;

    public function setConfig(array $config)
    {
        $this->config = $config;
    }


    /**
     * Get all the orders, filtered by Payment Status and Payment Type
     *
     * @param int $paymentStatus the Payment Status
     * @param int $paymentType the Payment Type
     *
     * @return array()
     */
    public function getOrderByPaymentStatusAndType($paymentStatus, $paymentType)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('o', 'c', 'g.' . $this->config['PG_MULPAY_ORDER_COL_PAYSTATUS'])
            ->from('\Eccube\Entity\Order', 'o')
            ->leftJoin('o.OrderStatusColor', 'c')
            ->innerJoin('\Plugin\GmoPaymentGateway\Entity\GmoOrderPayment', 'g', 'WITH', 'o.id = g.id')
            ->where($qb->expr()->andx(
                $qb->expr()->neq('o.OrderStatus', 8),
                $qb->expr()->eq('o.del_flg', 0),
                $qb->expr()->isNotNull('g.' . $this->config['PG_MULPAY_ORDER_COL_PAYID']))
            );

        if ($paymentStatus != null) {
            $qb
                ->andWhere($qb->expr()->eq('g.' . $this->config['PG_MULPAY_ORDER_COL_PAYSTATUS'], ':code1'))
                ->setParameter('code1', $paymentStatus);
        }
        if ($paymentType != null) {
            $qb
                ->andWhere($qb->expr()->eq('g.' . $this->config['PG_MULPAY_ORDER_COL_PAYID'], ':code2'))
                ->setParameter('code2', $paymentType);
        }
        $qb->orderBy('o.id', 'DESC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
